export const images = {
  backgroundImage: require('./images/loginBackground.png'),
  SignupBg: require('./images/SignupBg.png'),
  logoWhite: require('./images/logoWhite.png'),
  flipCard: require('./images/flip-card.png'),
  maximumBenefits: require('./images/maximumBenefits.png'),
  Logo: require('./images/Logo.png'),
  Insured: require('./images/per-insured.png'),
};

export const icons = {
  logo: require('./icons/logo.png'),
  leftArrow: require('./icons/leftArrow.png'),
  faceID: require('./icons/faceID.png'),
  fingerprint: require('./icons/fingerprint.png'),
  eyeClosed: require('./icons/eyeClosed.png'),
  eyeOpen: require('./icons/eyeOpen.png'),
  tickIcon: require('./icons/tickIcon.png'),
  backArrow: require('./icons/backArrow.png'),
  forgotPassword: require('./icons/forgotPassword.png'),
  email: require('./icons/email.png'),
  resetPassword: require('./icons/resetPassword.png'),
  search: require('./icons/search.png'),
  notification: require('./icons/notification.png'),
  menu: require('./icons/menu.png'),
  leftArrowStraight: require('./icons/leftArrowStraight.png'),
  rightArrowStraight: require('./icons/rightArrowStraight.png'),
  benefits: require('./icons/benifits.png'),
  rightArrowRound: require('./icons/rightArrowRound.png'),
  addSquare: require('./icons/add-square.png'),
  arrowUp: require('./icons/arrow-up.png'),
  person: require('./icons/person.png'),
  claim: require('./icons/claim.png'),
  chart: require('./icons/chart.png'),
  payment: require('./icons/payment-02.png'),
  paymentInactive: require('./icons/payment-inactive.png'),
  creditCard: require('./icons/credit-card.png'),
  editTask: require('./icons/task-edit.png'),
  toggleTop: require('./icons/toggleTop.png'),
  toggleBottom: require('./icons/arrow-down.png'),
  map: require('./icons/google-maps.png'),
  listIcon: require('./icons/list-icon.png'),
  labsInactive: require('./icons/labs.png'),
  hospital: require('./icons/hospital-02.png'),
  labsActive: require('./icons/labWhite.png'),
  hospitalInactive: require('./icons/hospital-inactive.png'),
  mapInactive: require('./icons/map-inactive.png'),
  listActive: require('./icons/list-active.png'),
  mapLoacationActive: require('./icons/mapLocationActive.png'),
  mapLoacationInActive: require('./icons/mapLocation-inactive.png'),
  calender: require('./icons/calender.png'),
  arrowDirection: require('./icons/arrow.png'),
  searchBlack: require('./icons/searchBlack.png'),
  searchWhite: require('./icons/searchWhite.png'),
  claimStats: require('./icons/claimStats.png'),
};
