export const images = {
  backgroundImage: require('./images/loginBackground.png'),
  SignupBg: require('./images/SignupBg.png'),
  maximumBenefits: require('./images/maximumBenefits.png'),
  Logo: require('./images/Logo.png'),
  Insured: require('./images/per-insured.png'),
  SecureFuture: require('./images/secure-future.png'),
  AddNew: require('./images/Add-New.png'),
};

export const icons = {
  logo: require('./icons/logo.png'),
  leftArrow: require('./icons/leftArrow.png'),
  faceID: require('./icons/faceID.png'),
  fingerprint: require('./icons/fingerprint.png'),
  eyeClosed: require('./icons/eyeClosed.png'),
  eyeOpen: require('./icons/eyeOpen.png'),
  tickIcon: require('./icons/tickIcon.png'),
  backArrow: require('./icons/backArrow.png'),
  forgotPassword: require('./icons/forgotPassword.png'),
  email: require('./icons/email.png'),
  resetPassword: require('./icons/resetPassword.png'),
  arrowUp: require('./icons/arrowUp.png'),
  arrowDown: require('./icons/arrowDown.png'),
  edit: require('./icons/edit.png'),
  delete: require('./icons/delete.png'),
  frame: require('./icons/frame.png'),
  personalDetail: require('./icons/personalDetail.png'),
  claimDetails: require('./icons/claimDetails.png'),
};
